# Generated by Django 6.1.1 on 2026-09-17 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester_offer_title",
                    models.CharField(
                        help_text="What skill the requester will teach in return",
                        max_length=200,
                    ),
                ),
                ("requester_offer_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_acceptance", "Pending Acceptance"),
                            ("escrow_deposit_required", "Escrow Deposit Required"),
                            ("locked_in_escrow", "Locked in Escrow (NOWPayments)"),
                            ("in_session", "In Session"),
                            (
                                "delivered_pending_peer",
                                "Delivered Pending Peer Confirmation",
                            ),
                            ("completed", "Completed (Escrow Released)"),
                            ("disputed", "Disputed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="escrow_deposit_required",
                        max_length=30,
                    ),
                ),
                ("session_date_proposal", models.CharField(blank=True, max_length=100)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, default="https://meet.google.com/swap-talent-room"
                    ),
                ),
                (
                    "escrow_deposit_usd",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
                ),
                (
                    "requester_delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Requester confirmed their session was taught",
                    ),
                ),
                (
                    "recipient_delivered",
                    models.BooleanField(
                        default=False,
                        help_text="Recipient confirmed their session was taught",
                    ),
                ),
                (
                    "escrow_released",
                    models.BooleanField(
                        default=False,
                        help_text="NOWPayments escrow refunded upon dual confirmation",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TalentListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="What you want to teach (e.g., Python & Django Backend Architecture)",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Programming & Tech", "Programming & Tech"),
                            ("Languages", "Languages"),
                            ("Design & Creative", "Design & Creative"),
                            ("Music & Audio", "Music & Audio"),
                            ("Business & Finance", "Business & Finance"),
                            ("Fitness & Wellness", "Fitness & Wellness"),
                            ("Academics & Science", "Academics & Science"),
                            ("Crafts & DIY", "Crafts & DIY"),
                        ],
                        default="Programming & Tech",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what you will teach"
                    ),
                ),
                (
                    "topics_covered",
                    models.JSONField(
                        default=list, help_text="List of topics or curriculum syllabus"
                    ),
                ),
                (
                    "teach_skills",
                    models.JSONField(
                        default=list,
                        help_text="Skills taught e.g., ['Django', 'REST APIs', 'PostgreSQL']",
                    ),
                ),
                (
                    "wanted_skills",
                    models.JSONField(
                        default=list,
                        help_text="Skills wanted in exchange e.g., ['React', 'TailwindCSS']",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("Beginner", "Beginner"),
                            ("Intermediate", "Intermediate"),
                            ("Advanced", "Advanced"),
                            ("Expert", "Expert"),
                        ],
                        default="Advanced",
                        max_length=20,
                    ),
                ),
                (
                    "session_format",
                    models.CharField(
                        choices=[
                            ("1-on-1 Live Video", "1-on-1 Live Video"),
                            (
                                "Pair Programming / Live Collab",
                                "Pair Programming / Live Collab",
                            ),
                            ("Async Review & Feedback", "Async Review & Feedback"),
                            ("Interactive Workshop", "Interactive Workshop"),
                        ],
                        default="1-on-1 Live Video",
                        max_length=40,
                    ),
                ),
                (
                    "session_duration_mins",
                    models.PositiveIntegerField(
                        default=60, help_text="Length of each session in minutes"
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=3)),
                (
                    "availability",
                    models.CharField(default="Evenings & Weekends UTC", max_length=150),
                ),
                (
                    "escrow_deposit_usd",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Refundable commitment deposit in USD processed via NOWPayments crypto escrow",
                        max_digits=6,
                    ),
                ),
                (
                    "student_prerequisites",
                    models.TextField(
                        blank=True, default="Basic curiosity and laptop with browser"
                    ),
                ),
                ("portfolio_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NowPaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("order_id", models.CharField(max_length=100)),
                ("order_description", models.TextField(blank=True)),
                ("price_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_currency", models.CharField(default="usd", max_length=10)),
                ("pay_amount", models.DecimalField(decimal_places=8, max_digits=18)),
                ("pay_currency", models.CharField(default="usdttrc20", max_length=15)),
                ("pay_address", models.CharField(max_length=120)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting for Payment"),
                            ("confirming", "Confirming on Blockchain"),
                            ("confirmed", "Confirmed"),
                            ("sending", "Sending Funds"),
                            ("finished", "Finished / In Escrow Vault"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded to Swapper"),
                            ("expired", "Expired"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("network", models.CharField(blank=True, max_length=30)),
                ("tx_hash", models.CharField(blank=True, max_length=150)),
                ("is_sandbox", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "swap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="backend_django.swaprequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="talent_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="swaps",
                to="backend_django.talentlisting",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Passionate Swapper", max_length=120),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "avatar_url",
                    models.URLField(
                        blank=True,
                        default="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
                    ),
                ),
                ("location", models.CharField(default="Remote", max_length=100)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("completed_swaps", models.PositiveIntegerField(default=0)),
                (
                    "crypto_wallet_address",
                    models.CharField(
                        blank=True,
                        help_text="User's payout address for refunded escrow",
                        max_length=100,
                    ),
                ),
                ("badges", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="talentlisting",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talents",
                to="backend_django.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_swap_requests",
                to="backend_django.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="swaprequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_swap_requests",
                to="backend_django.userprofile",
            ),
        ),
    ]
