# Generated by Django 6.1.1 on 2026-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_django", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentlisting",
            name="is_volunteer",
            field=models.BooleanField(
                default=False,
                help_text="If True, this listing is free - no escrow or exchange needed",
            ),
        ),
        migrations.AlterField(
            model_name="talentlisting",
            name="category",
            field=models.CharField(
                choices=[
                    ("Programming & Tech", "Programming & Tech"),
                    ("Languages", "Languages"),
                    ("Design & Creative", "Design & Creative"),
                    ("Music & Audio", "Music & Audio"),
                    ("Business & Finance", "Business & Finance"),
                    ("Fitness & Wellness", "Fitness & Wellness"),
                    ("Academics & Science", "Academics & Science"),
                    ("Crafts & DIY", "Crafts & DIY"),
                    ("Volunteering & Community", "Volunteering & Community"),
                ],
                default="Programming & Tech",
                max_length=50,
            ),
        ),
    ]
